### PR TITLE
[Bugfix/Enhancement] Ability to provide named parameters for formatter configuration

### LINKED ISSUE #21: Formatter configuration is not able to handle named parameters
Handler Parameter configuration can handle named parameters, therefore, the formatter configuration should handle those aswell.

### PR DESCRIPTION
**Pull request by boesing**
Fixes #21

### CODE REVIEW

**Comment by abacaphiliac** [comment]
this change set has several compatibility breaks. some of which are planned for v3.

are you interested in submitting a PR with simply the formatter configuration enhancement?

**Comment by boesing** [comment]
I've reverted those BC breaks since I didn't realize that the container you are passing does not have any Typehint within functions. Should be fine now.

**Comment by abacaphiliac** [comment]
awesome. thank you for doing that @boesing . i will continue review this evening.

**Comment by boesing** [comment]
Feel free. I just would like to use that feature 😊

**Comment by abacaphiliac** [comment]
@boesing thank you for your contribution.

https://github.com/enlitepro/enlite-monolog/releases/tag/v2.3.0

**Pull request merged**
