### PR TITLE
monolog v2 support and drop php < 7.2

### PR DESCRIPTION
**Pull request by snapshotpl**

### CODE REVIEW

**Comment by snapshotpl** [comment]
@abacaphiliac it's ready. I have to drop support for zf2 because it doesn't work correctly with php 7.3 and 7.4.

**Comment by snapshotpl** [comment]
@abacaphiliac ping

**Comment by snapshotpl** [comment]
@abacaphiliac can you take a look?

**Comment by abacaphiliac** [comment]
hi @snapshotpl,

first thing, let me say thank you for the dedication and care you have put into this effort. i sincerely apologize for the delay.

next, as it stands, there are quite a few breaking changes in this request. i think we are forced to target a 3.0 release, which is great because 3.0 has been roughly (very roughly) planned for quite some time now:
https://github.com/enlitepro/enlite-monolog/projects

i think the best course of action is as follows:
* i would create a tag for changes that have been merged into master since the last tag
* i would create a new protected branch from master for development of 3.0, with composer branch alias
* you would redirect this pull request to the 3.0 branch
* we would tackle the rest of the breaking changes slated for 3.0
* i would release 3.0 (after we have some consumer feedback on a stable candidate, of course)

i was tinkering with the ZF2 integration tests last night as i saw your commit message about it not working with the newest version(s) of PHP. i think i was able to come up with a way for us to maintain ZF2 and ZF3 compatibility, which i've done in a separate branch here:
https://github.com/enlitepro/enlite-monolog/compare/master...abacaphiliac:monolog-2?expand=1

here's the build for that proposal:
https://travis-ci.org/abacaphiliac/enlite-monolog/builds/627060591

that potential submission itself can definitely be broken up into a few smaller chunks, e.g. switch to infection from humbug, add prefer-lowest ZF2/3 integration builds, upgrade of all dev/build dependencies (not just phpunit), stage reconfiguration, and finally merging a compatible upgrade to monolog 2.

are you interested in pairing up on an alternative plan to the one above? if so, i was thinking we might be able to knock out some of these upgrades in the 2.x series together, while also continuing the great efforts that you've done in this request (e.g. implementing new syntax, tightening up the public APIs, enforcing strictness, etc.) and turning it into a complete 3.0 release. what do you think?

**Comment by snapshotpl** [comment]
Thanks for reply!

Since keep ZF2/3 compatibility make sense we already give possibility to smooth switch in v2. I would like to left it because it increase code complexity. I have more ideas to make this lib simple in v3 before final result.

About other things (humbug->infection, phpunit) - these are internal tools and aren't impact to end user, so imo we can change it once as it.

In summary:
- release current master,
- branch this changes to v3
- make some other work to v3 branch (even add removed zf2 support),
- release (we can also add zf2 support after v3 release if will be required),
- :beers:

**Comment by abacaphiliac** [comment]
@snapshotpl great, i'm glad we can work together on this. i'll throw a couple of small build PRs your way and i think together we'll be able to get your monolog v2 support into this project's 2.x.

**Comment by abacaphiliac** [comment]
@snapshotpl just checking in. are you still interested in getting a version of this into the next 2.x release?

**Comment by snapshotpl** [comment]
Yes. Next step is resolve conflicts here?

**Comment by abacaphiliac** [comment]
in this pull request i think the tests would need to be restored and the changes to the public interfaces (added typings) would need to be removed in addition to the conflict resolution. we do want these things (and others) in v3, though.

i think we've cleared the way for `monolog:^2`, `php:^7.2`, and `phpunit:^8`. unless i'm forgetting something, i think the dependency upgrades, resolution of phpunit deprecations, and short-array syntax are all that's left in order to release v2.5.

please feel free to save this PR for v3 and create a new PR for v2.5. conversely, conflict resolution here is fine and we'd address test removal and changes to public APIs another day. of course it's up to you how you'd like to proceed : )

**Comment by snapshotpl** [comment]
Already done in master

**Pull request closed without merging**
